In [66]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, lil_matrix, vstack, hstack, save_npz, load_npz, block_diag, identity, random
from scipy.sparse.linalg import inv, spsolve, splu
from scipy.linalg import lu, lu_factor, lu_solve
from concurrent.futures import ProcessPoolExecutor
from multiprocessing import Pool, shared_memory
import matplotlib.pyplot as plt
import time
import cProfile
import pstats 
import csv
import os 
from tqdm import tqdm


In [67]:
def lower_block_bidiagonal_nonsingular(n_blocks, block_size):
    """
    Generate a nonsingular sparse lower block bidiagonal matrix in CSR format.

    Parameters:
        n_blocks (int): Number of diagonal blocks.
        block_size (int): Size of each square block.

    Returns:
        scipy.sparse.csr_matrix: The resulting nonsingular sparse matrix.
        numpy.ndarray: The corresponding RHS vector.
    """
    N = n_blocks * block_size  # Total size of the matrix
    data, row_indices, col_indices = [], [], []

    # Generate diagonal (B_i) and lower diagonal (L_i) blocks
    for i in range(n_blocks):
        row_offset = i * block_size
        col_offset = i * block_size

        # Ensure nonzero entries in the main diagonal block (B_i)
        block_main = np.random.rand(block_size, block_size) + np.eye(block_size)  # Make B_i non-singular
        for r in range(block_size):
            for c in range(block_size):
                val = block_main[r, c]
                data.append(val)
                row_indices.append(row_offset + r)
                col_indices.append(col_offset + c)

        # Lower block (L_i), ensuring nonzero entries
        if i < n_blocks - 1:
            row_offset = (i + 1) * block_size
            col_offset = i * block_size
            block_lower = np.random.rand(block_size, block_size) + 0.5*np.eye(block_size) # Random values ensure nonzero entries

            for r in range(block_size):
                for c in range(block_size):
                    val = block_lower[r, c]
                    data.append(val)
                    row_indices.append(row_offset + r)
                    col_indices.append(col_offset + c)

    # Create sparse CSR matrix
    sparse_matrix = csr_matrix((data, (row_indices, col_indices)), shape=(N, N))

    # Generate a random RHS vector (column vector)
    rhs_vector = np.random.rand(N, 1)  # Nx1 dense vector

    return sparse_matrix, rhs_vector

In [69]:
block_size = 4
number_of_processors = 4

k_list = [4,5,6,7,8,9,10,11,12,13,14,15,16]
#k_list = [6]
# for k in tqdm(k_list):
#     n = int(number_of_processors*2**k)
#     number_of_blocks = n + 1
#     print(number_of_blocks)
#     M, f = lower_block_bidiagonal_nonsingular(number_of_blocks, block_size)
#     x = spsolve(M,f)
#     save_folder = f"Samples_to_test"
#     save_npz(f"{save_folder}/n{number_of_blocks}_b{block_size}_mat.npz",M)
#     np.save(f"{save_folder}/n{number_of_blocks}_b{block_size}_rhs.npy",f)
#     np.save(f"{save_folder}/n{number_of_blocks}_b{block_size}_sol.npy",x)

In [80]:

def create_full_permutation_matrix(m, block_size):
    num_blocks = m // block_size
    perm_order = []

    # First, append all odd-indexed blocks
    for i in range(0, num_blocks, 2):
        perm_order.append(i)

    # Then, append all even-indexed blocks
    for i in range(1, num_blocks, 2):
        perm_order.append(i)

    data, rows, cols = [], [], []

    for new_index, old_index in enumerate(perm_order):
        start_new = new_index * block_size
        start_old = old_index * block_size
        for i in range(block_size):
            data.append(1)              
            rows.append(start_new + i)  
            cols.append(start_old + i)  

    return csr_matrix((data, (rows, cols)), shape=(m, m))

def placeholder_name(M, f, block_size : int, processors : int):
    """ 
    Performs Block Cyclic Reduction (BCR) in parallel for solving lower block bidiagonal systems.

    Parameters:
    -----------
    M : scipy.sparse.csr_matrix or numpy.ndarray
        The coefficient matrix of size (N, N), where N = (n+1) * block_size.
        Must be a square lower block bidiagonal matrix.

    f : numpy.ndarray
        The right-hand side (RHS) vector of size (N, 1), corresponding to Mx = f.

    block_size : int
        The size of each block in the matrix.

    processors : int
        The number of processors used for parallel block cyclic reduction.

    Returns:
    --------
    x : numpy.ndarray
        The solution vector of size (N, 1) satisfying Mx = f.
    """
    N, L = M.shape
    assert N == L,  f"M must be sqaure but has dimensions {N}x{L}"
    n = (N - 1) // block_size
    assert n % processors == 0, f"M must have size (n+1)*block_size x (n+1)*block_size, where n = p * 2**k. p is not a multiple of n."
    nbyp = n // processors 
    assert ((nbyp & (nbyp-1) == 0) and nbyp != 0), f"M must have size (n+1)*block_size x (n+1)*block_size, where n = p * 2**k. n/p is not a power of two."
    number_of_steps = int(np.log2(nbyp)) # Number of steps in the forward step and backward step for each processor

    row_index_start = block_size
    row_index_end = block_size*(1+nbyp)
    col_index_start = 0
    col_index_end = block_size*(nbyp+1)
    
    # Divide among the processors
    M_k_list = []
    f_k_list = []
    B_k_s_list = []
    A_k_s_list = []
    f_k_s_list = []
    
    for _ in range(processors):
        # Perform the forward step
        M_copy = M[row_index_start:row_index_end, col_index_start:col_index_end]
        f_copy = f[row_index_start:row_index_end]
        M_k, f_k, B_k_s, A_k_s, f_k_s = forward_placeholder(M_copy, f_copy, block_size, processors, [], [], [])

        # Store the results for inter-processor communication
        M_k_list.append(M_k)
        f_k_list.append(f_k)

        # Store the results for the backward step
        B_k_s_list.append(B_k_s)
        A_k_s_list.append(A_k_s)
        f_k_s_list.append(f_k_s)

        # Update the indices for the next processor
        row_index_start = row_index_end
        row_index_end += nbyp*block_size 
        col_index_start = col_index_end - block_size
        col_index_end += block_size*nbyp
    
    x0 = spsolve(M[:block_size,:block_size],f[:block_size]) # The master of all processors
    base_case_x = [x0]

    # Only serial part of the algorithm
    for i in range(processors):
        B_k = M_k_list[i][:,:block_size]
        A_k = M_k_list[i][:,block_size:]
        f_k = f_k_list[i]
        x_next = spsolve(A_k,f_k.flatten()-B_k@base_case_x[i])
        base_case_x.append(x_next)
    
    final_x = np.array([])
    
    # Perform the backward step
    for i in range(processors):
        B_k_s = B_k_s_list[i] 
        A_k_s = A_k_s_list[i] 
        f_k_s = f_k_s_list[i] 

        x_for_current_processor = backward_placeholder(B_k_s, A_k_s, f_k_s, base_case_x[i:i+2], number_of_steps, block_size, processors)
        final_x = np.concatenate((final_x, x_for_current_processor))

    final_x = np.concatenate((final_x, base_case_x[-1]))
    return final_x
        
def forward_placeholder(M, f, block_size : int, processors : int, B_s = [], A_s = [], f_s = []):
    n,m = M.shape
    if n == block_size:
        return M,f,B_s,A_s,f_s
    
    M_next = csr_matrix((n//2,n//2+block_size))
    f_next = np.zeros(n//2)
    # Do one step
    for i in range(0,n,2*block_size):
        # Extract block elements from input
        B1 = M[i:i+block_size, i:i+block_size] 
        A1 = M[i:i+block_size, i + block_size: i + 2*block_size] 
        B2 = M[i + block_size: i + 2*block_size,i + block_size: i + 2*block_size ]
        A2 = M[i + block_size: i + 2*block_size,i + 2*block_size: i + 3*block_size]
        f1 = f[i:i+block_size]
        f2 = f[i + block_size: i + 2*block_size]

        # Store the values for the backward step
        B_s.append(B1)
        A_s.append(A1)
        f_s.append(f1)

        ####################
        # Convert blocks to dense arrays if they aren’t already.
        B1_dense = B1.toarray() if hasattr(B1, "toarray") else B1
        A1_dense = A1.toarray() if hasattr(A1, "toarray") else A1
        B2_dense = B2.toarray() if hasattr(B2, "toarray") else B2
        A2_dense = A2.toarray() if hasattr(A2, "toarray") else A2
        f1_dense = f1.toarray() if hasattr(f1, "toarray") else f1
        f2_dense = f2.toarray() if hasattr(f2, "toarray") else f2

        print(f"B1: {B1.toarray()}")
        print(f"A1: {A1.toarray()}")
        print(f"B2: {B2.toarray()}")
        print(f"A2: {A2.toarray()}")
        print(f"f1: {f1}")
        print("\n")

        # Use LU factorization with pivoting to "solve" for the necessary inverses.
        lu_A1, piv_A1 = lu_factor(A1_dense)
        lu_B2, piv_B2 = lu_factor(B2_dense)

        # Instead of explicitly forming inverses, we solve linear systems:
        new_B1 = lu_solve((lu_A1, piv_A1), B1_dense)
        new_A1 = -lu_solve((lu_B2, piv_B2), A2_dense)
        new_f1 = lu_solve((lu_A1, piv_A1), f1_dense) - lu_solve((lu_B2, piv_B2), f2_dense)
        ####################

        # Compute inverses and values for the next depth. This is equivalent to removing all odd indices from the input
        # B2_inv = inv(B2)
        # A1_inv = inv(A1)
        # new_B1 = A1_inv@B1
        # new_A1 = -B2_inv@A2
        # new_f1 = A1_inv@f1 - B2_inv@f2

        # Set the new values to obtain a reduced system of half the original size
        j = i//2
        M_next[j:j+block_size,j:j+block_size] = new_B1
        M_next[j:j+block_size,j+block_size:j+2*block_size] = new_A1
        f_next[j:j+block_size] = new_f1.flatten()

    # Recursively apply the same procedure
    return forward_placeholder(M_next,f_next,block_size,processors,B_s,A_s,f_s)

def backward_placeholder(B_s, A_s, f_s, x_s, number_of_steps : int, block_size : int, processors : int):
    x_result = x_s[0]
    power = 0
    for i in range(number_of_steps-1,-1,-1):
        j = -(2**power - 1) if power > 0 else None
        k = -(2**(power+1) - 1)

        B = B_s[k:j]
        A = A_s[k:j]
        f = f_s[k:j]

        A_for_solve = block_diag(A, format='csr')
        B_for_solve = block_diag(B, format='csr')
        f_for_solve = np.concatenate(f).flatten()
        x_for_solve = x_result.copy()   

        x_new = spsolve(A_for_solve,f_for_solve - B_for_solve@x_for_solve)

        x_result = np.concatenate((x_result,x_new))
        Q = create_full_permutation_matrix(x_result.shape[0], block_size)
        x_result = Q.T@x_result
        power += 1
    return x_result


In [81]:
save_folder = "Samples_to_test"
n_blocks = int(number_of_processors*2**k_list[2]) + 1
print(n_blocks)
M,f,x = load_npz(f"{save_folder}/n{n_blocks}_b{number_of_processors}_mat.npz"), np.load(f"{save_folder}/n{n_blocks}_b{number_of_processors}_rhs.npy"), np.load(f"{save_folder}/n{n_blocks}_b{number_of_processors}_sol.npy")

257


In [82]:
start = time.time()
x_sol = placeholder_name(M,f,block_size=block_size,processors=number_of_processors)
end = time.time()
print(f"Time taken: {end-start} seconds")
print("Error,", np.linalg.norm(x - x_sol))

B1: [[0.57693156 0.23495015 0.86471442 0.31319552]
 [0.08561308 1.46001739 0.75987638 0.78138304]
 [0.81385828 0.12427368 1.00446813 0.41223398]
 [0.86920012 0.0608789  0.15378273 1.14254919]]
A1: [[1.51852213 0.27303734 0.78216878 0.54260429]
 [0.96689837 1.97137891 0.56234122 0.9908077 ]
 [0.21563256 0.42039753 1.83874595 0.84898222]
 [0.23550704 0.42990741 0.53535583 1.86291688]]
B2: [[1.21606476 0.54734649 0.40009564 0.40449604]
 [0.85309535 1.40806698 0.78363855 0.51931356]
 [0.62278193 0.43182203 1.23803453 0.66017185]
 [0.47958793 0.65341147 0.14606652 1.38770634]]
A2: [[1.86697062 0.98428518 0.6913501  0.6676905 ]
 [0.72177821 1.78367713 0.40841357 0.12255264]
 [0.15488802 0.6275794  1.98070373 0.8253167 ]
 [0.53981993 0.88967722 0.68331733 1.70022072]]
f1: [[0.77130938]
 [0.59715824]
 [0.61372992]
 [0.56666121]]


B1: [[1.06682215 0.21693907 0.22037655 0.18890151]
 [0.88048118 0.88807132 0.75714731 0.07846572]
 [0.61545074 0.53962906 0.56893507 0.71718556]
 [0.58631333 0.76798

c:\Users\tinus\Desktop\Cyclic-Reduction\.venv\Lib\site-packages\scipy\sparse\_index.py:197: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)


B1: [[-0.69279215 -0.01292471  0.256336   -0.61944409]
 [ 1.43692393 -0.22880888 -0.70173884  2.11270393]
 [-1.3569583  -0.15177465  0.24941566 -2.32109868]
 [-0.30771097 -0.01346074 -0.06362047 -0.06458314]]
A1: [[-27.16150269   7.45807872  13.72213534  -8.04507262]
 [ 23.57099354  -5.050081   -11.34910949   6.98595034]
 [-12.3834137   -2.50173687   3.70856206   2.97156666]
 [ 19.0086244   -2.25698333  -7.10671489   3.55584512]]
B2: [[-0.33505482 -0.06820672  0.2822474   0.05456385]
 [-0.34990038 -0.36711255 -0.3693817  -0.11008982]
 [-0.07019294 -0.08259889 -0.39757823 -0.17678944]
 [ 0.02769915 -0.15114371  0.10879854 -0.08827477]]
A2: [[ 0.62741906 -1.90374589  0.02142702 -2.91733021]
 [ 0.07879911  3.65755379  0.21050474  5.09093988]
 [ 0.06890139  1.05703014  1.77628753  1.24183362]
 [ 0.0953204  -0.11396656 -0.12000812  0.80747329]]
f1: [-0.54561144 -0.11636976 -1.08499672  2.14928364]


B1: [[-0.32333091 -0.18893692 -0.45852269  0.2076065 ]
 [-0.0865488  -0.46615933 -0.48684854

In [72]:
import numpy as np
from scipy.sparse import issparse
from scipy.sparse.linalg import svds

def compute_condition_number(A, norm=2):
    """
    Compute the condition number of a square matrix A.
    
    Parameters:
        A : numpy.ndarray or scipy.sparse matrix
            The square matrix whose condition number is to be computed.
        norm : {2, -1, -np.inf, 'fro'}, optional
            The matrix norm to use. For norm=2, the condition number is computed via
            singular values. For other norms, np.linalg.cond is used on a dense array.
            (Default is 2, which is common for spectral norm.)
    
    Returns:
        cond_number : float
            The computed condition number of A.
    """
    # For sparse matrices, if the matrix is small, convert to dense;
    # otherwise, use a sparse SVD for the 2-norm.
    if issparse(A):
        n, m = A.shape
        if n != m:
            raise ValueError("Matrix must be square.")
        
        # Use dense conversion if the matrix is moderate in size.
        # Adjust the threshold as needed.
        if n < 500:
            A_dense = A.toarray()
            cond_number = np.linalg.cond(A_dense, p=norm)
        else:
            # For norm=2, estimate the largest and smallest singular values.
            if norm == 2:
                # Compute the largest singular value.
                sigma_max = svds(A, k=1, which='LM', return_singular_vectors=False)[0]
                # Compute the smallest singular value.
                sigma_min = svds(A, k=1, which='SM', return_singular_vectors=False)[0]
                cond_number = sigma_max / sigma_min
            else:
                # For other norms, convert to dense (or implement another method).
                A_dense = A.toarray()
                cond_number = np.linalg.cond(A_dense, p=norm)
    else:
        # Dense case.
        cond_number = np.linalg.cond(A, p=norm)
    
    return cond_number

print(compute_condition_number(M))

464.42048890802516


In [73]:
import numpy as np
from scipy.sparse import issparse

def compute_lower_bidiagonal_block_condition_numbers(M, block_size, norm=2):
    """
    Given a lower block-bidiagonal matrix M with blocks of size `block_size`, compute the condition numbers 
    for each block in the following manner:
    
        Row 0: Only A_0 exists, so its condition number is computed.
        For each row i >= 1:
            - B_i is the off-diagonal block (located in columns [(i-1)*block_size, i*block_size])
            - A_i is the diagonal block (located in columns [i*block_size, (i+1)*block_size])
    
    Parameters:
        M : numpy.ndarray or scipy.sparse matrix
            The full square matrix of size (n_blocks * block_size) x (n_blocks * block_size) having the structure:
            
                [ A_0       0      0    ... ]
                [ B_1      A_1     0    ... ]
                [  0       B_2    A_2   ... ]
                [ ...      ...    ...   ... ]
            
        block_size : int
            The size of each square block.
        norm : {2, -1, -np.inf, 'fro'}, optional
            The matrix norm to use when computing the condition number (default is 2, the spectral norm).
    
    Returns:
        cond_dict : dict
            A dictionary where:
              - Key 0 maps to the condition number of A_0.
              - For each i >= 1, key i maps to a tuple (cond(B_i), cond(A_i)).
    """
    # Convert M to a dense array if it's sparse.
    if issparse(M):
        M_dense = M.toarray()
    else:
        M_dense = M

    n, m = M_dense.shape
    if n != m:
        raise ValueError("Matrix must be square.")
    if n % block_size != 0:
        raise ValueError("Matrix dimensions must be an integer multiple of block_size.")
    
    nblocks = n // block_size
    cond_dict = {}
    
    # Block row 0: Only the diagonal block A_0 is present.
    A0 = M_dense[0:block_size, 0:block_size]
    cond_dict[0] = np.linalg.cond(A0, p=norm) if not np.allclose(A0, 0) else np.inf
    
    # For each subsequent block row i (i >= 1), compute:
    # - cond(B_i) for the off-diagonal block from the previous column block.
    # - cond(A_i) for the diagonal block.
    for i in range(1, nblocks):
        Bi = M_dense[i*block_size:(i+1)*block_size, (i-1)*block_size:i*block_size]
        Ai = M_dense[i*block_size:(i+1)*block_size, i*block_size:(i+1)*block_size]
        cond_Bi = np.linalg.cond(Bi, p=norm) if not np.allclose(Bi, 0) else np.inf
        cond_Ai = np.linalg.cond(Ai, p=norm) if not np.allclose(Ai, 0) else np.inf
        cond_dict[i] = (cond_Bi, cond_Ai)
    
    return cond_dict

cond_dict = compute_lower_bidiagonal_block_condition_numbers(M, block_size)

In [74]:
cond_dict

{0: np.float64(5.095762668578615),
 1: (np.float64(371.1833620978607), np.float64(3.569494746853606)),
 2: (np.float64(4.715260039007898), np.float64(3.8600330509838634)),
 3: (np.float64(10.293772735802223), np.float64(4.936761834650847)),
 4: (np.float64(12.843227921018993), np.float64(3.9806215849566264)),
 5: (np.float64(78.41583693078363), np.float64(2.62933043306802)),
 6: (np.float64(75.18213053080198), np.float64(5.228263806771458)),
 7: (np.float64(17.436647275669763), np.float64(7.8207996127876935)),
 8: (np.float64(7.79965702660231), np.float64(3.5034011229645694)),
 9: (np.float64(13.157372492245667), np.float64(3.437915267122757)),
 10: (np.float64(8.575774028027844), np.float64(4.126129833159588)),
 11: (np.float64(10.027345471565603), np.float64(6.724178396735518)),
 12: (np.float64(12.573812258489507), np.float64(3.6469941901919745)),
 13: (np.float64(14.584421707182175), np.float64(4.232420430471104)),
 14: (np.float64(62.178817869280536), np.float64(11.345875798608278